 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assortments", type: :request do
  # Assortment. As you add validations to Assortment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Assortment.create! valid_attributes
      get assortments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      assortment = Assortment.create! valid_attributes
      get assortment_url(assortment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_assortment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      assortment = Assortment.create! valid_attributes
      get edit_assortment_url(assortment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Assortment" do
        expect {
          post assortments_url, params: { assortment: valid_attributes }
        }.to change(Assortment, :count).by(1)
      end

      it "redirects to the created assortment" do
        post assortments_url, params: { assortment: valid_attributes }
        expect(response).to redirect_to(assortment_url(Assortment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Assortment" do
        expect {
          post assortments_url, params: { assortment: invalid_attributes }
        }.to change(Assortment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post assortments_url, params: { assortment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assortment" do
        assortment = Assortment.create! valid_attributes
        patch assortment_url(assortment), params: { assortment: new_attributes }
        assortment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the assortment" do
        assortment = Assortment.create! valid_attributes
        patch assortment_url(assortment), params: { assortment: new_attributes }
        assortment.reload
        expect(response).to redirect_to(assortment_url(assortment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        assortment = Assortment.create! valid_attributes
        patch assortment_url(assortment), params: { assortment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested assortment" do
      assortment = Assortment.create! valid_attributes
      expect {
        delete assortment_url(assortment)
      }.to change(Assortment, :count).by(-1)
    end

    it "redirects to the assortments list" do
      assortment = Assortment.create! valid_attributes
      delete assortment_url(assortment)
      expect(response).to redirect_to(assortments_url)
    end
  end
end
