SITE_NAME:        "Highlighter"
TAGLINE:          "Highlight passages from your favorite reading moments."
SITE_URL:         "https://highlighter.online"
SUPPORT_EMAIL:    "smcalilly@gmail.com"

development:
  SITE_DOMAIN: "localhost:3000"
  MAILER_HOST: "localhost:3000"
test:
  MAILER_HOST: "localhost:3000"
production:
  SITE_DOMAIN: "highlighter.online"
  MAILER_HOST: "highlighter.online"